---
apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db01
  namespace: db
spec:
  instances: 2

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
