repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: kedacore
  url: https://kedacore.github.io/charts
- name: local-path-provisioner
  url: git+https://github.com/rancher/local-path-provisioner@deploy/chart?ref=v0.0.25
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server/

releases:
#- name: local-path-provisioner
#  namespace: local-path-provisioner
#  chart: local-path-provisioner/local-path-provisioner
#  set:
#  - name: storageClass.defaultClass
#    value: true
- name: promstack
  namespace: prom-system
  chart: prometheus-community/kube-prometheus-stack
- name: keda
  namespace: keda-system
  chart: kedacore/keda
- name: rabbitmq
  namespace: rabbitmq-system
  chart: bitnami/rabbitmq-cluster-operator
- name: cnpg
  namespace: cnpg-system
  chart: cnpg/cloudnative-pg
- name: metrics-server
  namespace: kube-system
  chart: metrics-server/metrics-server
  values:
  - args: [ "--kubelet-insecure-tls" ]
