---
apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: v1
kind: Secret
metadata:
  name: enix-user
  namespace: db
data:
  username: ZW5peAo=
  password: cGFzc3dvcmQK
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db01
  namespace: db
spec:
  instances: 2
  bootstrap:
    initdb: #  Setup the database.
      database: messages
      owner: enix
      encoding: UTF-8
      secret:
        name: enix-user
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
