---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace : {{ .Release.Namespace }}
spec:
  instances: 2
  bootstrap:
    initdb: #  Setup the database.
      database: messages
      postInitApplicationSQL:
        - |
          SET ROLE messages;
          CREATE TABLE application_numbers (i integer);
          INSERT INTO application_numbers (SELECT generate_series(1,10000));
          CREATE TABLE messages (id varchar(50), message varchar(255), hostname varchar(50));

  # Require 1Gi of space
  storage:
    size: 1Gi
