apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
  - type: Container  
    default: # this section defines default limits
      cpu: 1
      memory: 100M
    defaultRequest: # this section defines default requests
      cpu: 0.1
      memory: 100M
