---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: mq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 500Mi
    limits:
      cpu: 2
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      # I think this disables the default guest account.
      loopback_users.guest = false
