---
repositories:
- name: benthos
  url: https://benthosdev.github.io/benthos-helm-chart/

---
environments:

  demo1: # no scaling and generator set to 0.1s (10/s) then crash
    values:
      - generator_interval: "1s"
      - generator_replica: 1
      - api_autoscaling_enabled: false
      - api_replica: 1
      - api_autoscaling_memory: 70
      - consumer_autoscaling_enabled: false
      - consumer_replica: 1 
      - consumer_autoscaling_cpu: 60
      - keda_enabled: false

  demo2: # manual scaling
    values:
      - generator_interval: "1s"
      - generator_replica: 3
      - api_autoscaling_enabled: false
      - api_replica: 5
      - api_autoscaling_memory: 70
      - consumer_autoscaling_enabled: false
      - consumer_replica: 1
      - consumer_autoscaling_cpu: 60
      - keda_enabled: false

  demo3:
    values:
      - generator_interval: "1s"
      - generator_replica: 3
      - api_autoscaling_enabled: true
      - api_replica: 10
      - api_autoscaling_memory: 70
      - consumer_autoscaling_enabled: false
      - consumer_replica: 1
      - consumer_autoscaling_cpu: 70
      - keda_enabled: false

  demo4:
    values:
      - generator_interval: "1s"
      - generator_replica: 3
      - api_autoscaling_enabled: true
      - api_replica: 10
      - api_autoscaling_memory: 70
      - consumer_autoscaling_enabled: true
      - consumer_replica: 3
      - consumer_autoscaling_cpu: 70
      - keda_enabled: false

  demo5:
    values:
      - generator_interval: "1s"
      - generator_replica: 3
      - api_autoscaling_enabled: true
      - api_replica: 10
      - api_autoscaling_memory: 70
      - consumer_autoscaling_enabled: false
      - consumer_replica: 1
      - consumer_autoscaling_cpu: 70
      - keda_enabled: true

  purge:
    values:
      - generator_interval: "1s"
      - generator_replica: 0
      - api_autoscaling_enabled: true
      - api_replica: 10
      - api_autoscaling_memory: 70
      - consumer_autoscaling_enabled: false
      - consumer_replica: 1
      - consumer_autoscaling_cpu: 70
      - keda_enabled: true

---
# Build the AMQP connection URL used in producer and consumer
{{- $username := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/username" .Namespace) }}
{{- $password := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/password" .Namespace) }}
{{- $host     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/host"     .Namespace) }}
{{- $port     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/port"     .Namespace) }}
{{- $amqpurl  := printf "amqp://%s:%s@%s:%s/" $username $password $host $port }}

releases:

- name: benthos-generator
  chart: benthos/benthos
  values: [ ./values-benthos-generator.yml ]
  version: 2.1.1
  set:
  - name: config.input.generate.interval
    value: {{ .Environment.Values.generator_interval }}
  - name: deployment.replicaCount
    value: {{ .Environment.Values.generator_replica }}

- name: benthos-api
  chart: benthos/benthos
  values: [ ./values-benthos-api.yml ]
  version: 2.1.1
  set:
  - name: config.output.amqp_0_9.urls[0]
    value: {{ $amqpurl }}
  - name: deployment.replicaCount
    value: {{ .Environment.Values.api_replica }}
  - name: autoscaling.maxReplicas
    value: {{ .Environment.Values.consumer_replica }}
  - name: autoscaling.enabled
    value: {{ .Environment.Values.api_autoscaling_enabled }}
  - name: autoscaling.maxReplicas
    value: {{ .Environment.Values.api_replica }}
  - name: autoscaling.metrics[0].resource.target.averageUtilization
    value: {{ .Environment.Values.api_autoscaling_memory }}

- name: benthos-consumer
  chart: benthos/benthos
  values: [ ./values-benthos-consumer.yml ]
  version: 2.1.1
  set:
  - name: config.output.sql_insert.dsn
    value: {{ fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/db-app/uri" .Namespace) }}
  - name: config.input.amqp_0_9.urls[0]
    value: {{ $amqpurl }}
  - name: autoscaling.enabled
    value: {{ .Environment.Values.consumer_autoscaling_enabled }}
  - name: deployment.replicaCount
    value: {{ .Environment.Values.consumer_replica }}
  - name: autoscaling.maxReplicas
    value: {{ .Environment.Values.consumer_replica }}
  - name: autoscaling.metrics[0].resource.target.averageUtilization
    value: {{ .Environment.Values.consumer_autoscaling_cpu }}

{{ if .Values.keda_enabled }}
- name: keda-consumer
  chart: ./chart/keda
  set:
  - name: triggerURI
    value: {{ $amqpurl }}
  - name: queueName
    value: "q1"
  - name: minReplicaCount
    value: 1
  - name: maxReplicaCount
    value: 25
  - name: targetName
    value: "benthos-consumer"
  - name: pollingInterval
    value: 30
  - name: cooldownPeriod
    value: 10
  - name: triggerMode
    value: "QueueLength"
  - name: triggerValue
    value: 1000
{{ end }}

# Note: it is mandatory to pass the namespace to helmfile!
# E.g.:
#    prod
