---
repositories:
- name: benthos
  url: https://benthosdev.github.io/benthos-helm-chart/

---
environments:
  default:
    values:
      - textsynth_sidecar: false
      - textsynth_api_endpoint: http://textsynth:8020/v1/engines/mistral_7B_q4/completions
  sidecar:
    values:
      - textsynth_sidecar: true
      - textsynth_api_endpoint: http://localhost:8020/v1/engines/mistral_7B_q4/completions

---

# Build the AMQP connection URL used in producer and consumer
{{- $username := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/username" .Namespace) }}
{{- $password := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/password" .Namespace) }}
{{- $host     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/host"     .Namespace) }}
{{- $port     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/port"     .Namespace) }}
{{- $amqpurl  := printf "amqp://%s:%s@%s:%s/" $username $password $host $port }}

releases:

- name: benthos-generator
  chart: benthos/benthos
  version: 2.1.1
  values:
    - ./values-benthos-generator.yml
    - extraVolumes:
        - name: data
    - extraVolumeMounts:
        - name: data
          mountPath: /data
    - initContainers:
        - name: fetchdata
          image: nixery.dev/shell/curl/jq
          command:
          - sh
          - -c
          - |
            curl -fsSL https://gitlab.com/xavki/tutoriels-python/-/raw/master/cities.json | jq -c .[] > /data/cities.jsonl
          volumeMounts:
            - name: data
              mountPath: /data

- name: benthos-api
  chart: benthos/benthos
  version: 2.1.1
  values: [ ./values-benthos-api.yml ]
  set:
  - name: config.output.amqp_0_9.urls[0]
    value: {{ $amqpurl }}

- name: benthos-consumer
  chart: benthos/benthos
  version: 2.1.1
  values: [ ./values-benthos-consumer.yml ]
  set:
  - name: config.output.sql_insert.dsn
    value: {{ fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/db-app/uri" .Namespace) }}
  - name: config.input.amqp_0_9.urls[0]
    value: {{ $amqpurl }}
  - name: config.pipeline.processors[0].branch.processors[0].http.url
    value: {{ .Environment.Values.textsynth_api_endpoint }}
  {{ if .Environment.Values.textsynth_sidecar }}
  strategicMergePatches:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: benthos-consumer
      spec:
        template:
          spec:
            volumes:
            - name: cache
              hostPath:
                path: /opt/textsynth
                type: DirectoryOrCreate
            containers:
            - image: jpetazzo/textsynth
              name: textsynth
              volumeMounts:
              - name: cache
                mountPath: /opt/textsynth
              readinessProbe:
                httpGet:
                  port: 8020
              resources:
                requests:
                  memory: 7G
                  cpu: 2.5
                limits:
                  memory: 7G
                  cpu: 64
  {{ end }}

{{ if false }}
- name: keda-consumer
  chart: ./chart/keda
  set:
  - name: triggerURI
    value: {{ $amqpurl }}
  - name: queueName
    value: "q1"
  - name: minReplicaCount
    value: 1
  - name: maxReplicaCount
    value: 25
  - name: targetName
    value: "benthos-consumer"
  - name: pollingInterval
    value: 30
  - name: cooldownPeriod
    value: 10
  - name: triggerMode
    value: "QueueLength"
  - name: triggerValue
    value: 1000
{{ end }}

# Note: it is mandatory to pass the namespace to helmfile!
# E.g.:
# helmfile -n app [-e sidecar]
