repositories:
- name: benthos
  url: https://benthosdev.github.io/benthos-helm-chart/

# Build the AMQP connection URL used in producer and consumer
{{- $username := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/username" .Namespace) }}
{{- $password := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/password" .Namespace) }}
{{- $host     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/host"     .Namespace) }}
{{- $port     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/port"     .Namespace) }}
{{- $amqpurl  := printf "amqp://%s:%s@%s:%s/" $username $password $host $port }}


environments:

  test1:
    values:
      - producer_interval: "0.1s"
      - autoscaling_enabled: false
      - consumer_replica: 5
      - consumer_autoscaling_cpu: 60

  test2:
    values:
      - producer_interval: "0.001s"
      - autoscaling_enabled: true
      - consumer_replica: 10
      - consumer_autoscaling_cpu: 70

releases:
- name: benthos-producer
  chart: benthos/benthos
  values: [ ./values-benthos-producer.yml ]
  version: 2.1.1
  set:
  - name: config.output.amqp_0_9.urls[0]
    value: {{ $amqpurl }}
  - name: config.input.generate.interval
    value: {{ .Environment.Values.producer_interval  }}
- name: benthos-consumer
  chart: benthos/benthos
  values: [ ./values-benthos-consumer.yml ]
  version: 2.1.1
  set:
  - name: config.output.sql_insert.dsn
    value: {{ fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/db-app/uri" .Namespace) }}
  - name: config.input.amqp_0_9.urls[0]
    value: {{ $amqpurl }}
  - name: autoscaling.enabled
    value: {{ .Environment.Values.autoscaling_enabled }}
  - name: deployment.replicaCount
    value: {{ .Environment.Values.consumer_replica }}
  - name: autoscaling.maxReplicas
    value: {{ .Environment.Values.consumer_replica }}
  - name: autoscaling.metrics[0].resource.target.averageUtilization
    value: {{ .Environment.Values.consumer_autoscaling_cpu }}

# Note: it is mandatory to pass the namespace to helmfile!
# E.g.:
#    prod
