#commonLabels:
#  release: promstack
config: 
  input:
    generate: 
      interval: "0.01s"
      mapping: |
        let customers = ["Xavier","Jérôme","Aurélien","Tifaine"]
        let rand_user_id = random_int(min: 0, max: 3)
        let locations = ["Paris","Berlin","NewYork","Pékin"]
        let rand_location_id = random_int(min: 0, max: 3)
        let order1 = uuid_v4()
        let order2 = uuid_v4()
        let userid = $customers.index($rand_user_id)
        let location = $locations.index($rand_location_id)
        root.user = { "id": $userid, "location": $location}
        root.orders = [{"uuid": $order1.string()}, {"uuid": $order2.string()}]
        root.priority = random_int(min: 0, max: 10)
  output:
    http_client:
      url: "http://benthos-api:8080/api/v2/register-orders"
      verb: POST
      headers:
        Content-Type: application/json

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
metrics:
  prometheus:
    add_process_metrics: true
    add_go_metrics: true
serviceMonitor:
  enabled: true

