---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 2
  bootstrap:
    initdb: #  Setup the database.
      database: messages
      postInitApplicationSQL:
        - |
          SET ROLE messages;
          -- CREATE TABLE application_numbers (i integer);
          -- INSERT INTO application_numbers (SELECT generate_series(1,10000));
          CREATE TABLE messages (
            id SERIAL PRIMARY KEY,
            uuid UUID,
            city VARCHAR(50),
            prompt TEXT,
            completion TEXT,
            submitted_at TIMESTAMP,
            generated_at TIMESTAMP
          );
  resources:
    requests:
      memory: 1G
      cpu: 0.1
    limits:
      memory: 1G
      cpu: 1
  storage:
    size: 1Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: db
  namespace: app
  labels:
    release: promstack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: db
  podMetricsEndpoints:
  - port: metrics