crds:
  install: true
operator:
  name: keda-operator
  replicaCount: 1
metricsServer:
  dnsPolicy: ClusterFirst
  useHostNetwork: false
rbac:
  create: true
serviceAccount:
  create: true
  name: keda-operator
